application: uudisreader
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|svg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|svg))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app